### ISSUE TITLE
[Idea] PickerCell Option - when # of selected items = # Maximum, exit

### ISSUE THREAD

**Issue by torrobinson** [muak/AiForms.Renderers#10]
First of all, THANKYOU for doing this. I'm 5 days into writing something like this myself for a work project after being shocked at how bare-bones and lacking Xamarin Forms is, especially around TableViews. I'm behind on my project and decided to search NuGet 1 last time, and ran into this repository. This is a lifesaver!

Something I had going in my personal attempt is that if the PickerCell being used only has 1 item, the menu would hide and jump back after 1 item was picked.

Does it sound reasonable to have an option that means something like "Once number of maximum selection has been reached, jump back to the TableView"?

For example, if I have a PickerCell where the user can only pick 1 item, and they enter the list of options and tap 1 option, it would immediately jump back to the previous page automatically.

This might be helpful on lists where there's not that many options and the options are small and simple, or there's many PickerCells to fill in and having to click "back" over and over feels tedious.

**Comment by muak** [comment]
@torrobinson 
Thank you for trying this library!
Your idea is good.
I consider implementing it.

**Comment by matteopiccioni** [comment]
I like this idea! 👍
