### ISSUE TITLE
IsEnabled/IsVisible usage

### ISSUE THREAD

**Issue by torrobinson** [muak/AiForms.Renderers#11]
Hello, 

I'm dynamically creating `Sections` with `PickerCells` within them that look like:

Object [**1**, 2, 3]
SubObject [1.1, 1.2, 1.3 - options are based off of selected Object]

When an Object is picked that has 0 SubObjects, I'd like to disable the SubObject `PickerCell` because I have no options to provide it and don't want the user to tap it.

I've tried setting `IsEnabled` to `false` on the Object `PickerCell` but it's still tappable.

Does `IsEnabled` work on `PickerCells`? Or, ideally, can `IsVisible` be used on them?

Thanks

**Comment by muak** [comment]
@torrobinson 
I'm sorry that Cell's IsEnabled isn't supported.

However, you can use Section's IsVisible.
You should make the main PickerCell and the sub PickerCell set in each other section.
And depending on the status of the main PickerCell, you make it change that IsVisible of the section which has the sub PickerCell.

Please try it.
