### ISSUE TITLE
PickerCell in Section hidden/show - Ghost value

### ISSUE THREAD

**Issue by matteopiccioni** [muak/AiForms.Renderers#16]
Hello,
In my SettingsView there are 3 Sections (Sec1, Sec2 and Sec3)
Sec1 contain 2 CheckBoxes 
The other 2 Sections (Sec2 and Sec3) are displayed only one at a time, through the IsVisible property (using the CheckBoxes checked status).
In Sec2 and Sec3 there are one or more Pickers.

If I select an object in the Picker of Sec2 (eg 'pippo') and Save, 
the value is rightly displayed into ValueText of Picker Cell.

But if I hide Sec2 and show Sec3,
than in the first picker of Sec3 I already see 'pippo' value selected,
although for this picker I still have not made any selection and even if 'pippo' does not exist in the picker list.

Thanks

**Comment by matteopiccioni** [comment]
Even using PickerCell instead of two Checkbox,
where I back to main page the old selected value is displayed

**Comment by muak** [comment]
@matteopiccioni 
Thank you for reporting a issue.

I didn't reproduce this issue.
I would appreciate it if you could write more specific the same as #15 .

**Comment by matteopiccioni** [comment]
Hello, sorry for late reply. 
The error is still here, please see attached project

The step to follow:
- In first PickerCell select 'letter'
- In second PickerCell select letter 'b' (for example)
- In first PickerCell select 'number'
- ERROR: In second PickerCell the letter 'b' is still visible, even if you clear SelectedItems and ItemSource

The project is only for Android, but should be also in iOS

[TestAiForms.zip](https://github.com/muak/AiForms.Renderers/files/2277095/TestAiForms.zip)

**Comment by muak** [comment]
@matteopiccioni 

Thank you for your detail report.

I have confirmed and could reproduce it.
I have just started fixing this issues. Please wait for some while.

**Comment by muak** [comment]
@matteopiccioni 

This issue has fixed.
Please use ver.0.2.9.
