### ISSUE TITLE
NumberPickerCell: Specifiy steps/items

### ISSUE THREAD

**Issue by FlashTek** [muak/AiForms.Renderers#17]
I would like to use a `NumberPickerCell` cell to let the user choose an integer which can either be `15, 30, 60, 90, 120, 150`. Therefore, I would either like to specify the items or set the steps in which the items appear in the number picker.

Otherwise: Maybe the usage of a `PickerCell` is more appropriate for this case. Is there a way to say that exactly one item has to be selected every time? I only found a setting to say that the maximal selected number is 1.

**Comment by muak** [comment]
@FlashTek 

NumberPicker has no way to specify steps or items in Android. So NumberPickerCell can't be implemented that.

As you said, using PickerCell is better than using NumberPicker. 
You should specify 1 at MaxSelectedNumber property. And PickerCell will become single select mode.

Please try it.
