### ISSUE TITLE
TextPickerCell

### ISSUE THREAD

**Issue by codegrue** [muak/AiForms.Renderers#24]
Thoughts on creating a basic picker for just a list of strings? 

Instead of going to a new page on iOS it would show a selection wheel at the bottom like the NumberPickerCell. This could be pretty much the same code as NumberPickerCell but would expose the Items property to pass in a set of strings to be the choices. It would also work like the new built-in Xamarin picker:

                        <sv:TextPickerCell Title="Color" SelectedItem="Red">
                            <sv:TextPickerCell.Items>
                                <x:String>Red</x:String>
                                <x:String>Green</x:String>
                                <x:String>Blue</x:String>
                            </sv:TextPickerCell.Items>  
                        </sv:TextPickerCell>

**Comment by codegrue** [comment]
I forked the code and will play with making one if that is okay with you.

**Comment by muak** [comment]
@codegrue 

Thank you for your pull request.

I'm confirming it now 
I think it is a very nice cell.

I want to modify to be able to use the others value type such as int, enum and double for Items property, I hope you will understand this.

**Comment by codegrue** [comment]
Thank you for adding it in. I agree on enhancing it. I would like to make the items collection bindable. Enum support would be good too. I will need some of that functionality eventually so if you don’t add it I will make the enhancements.

Also, thanks for making this project. It’s way better than the build in form.

Jeff
