### ISSUE TITLE
Toggling Section title

### ISSUE THREAD

**Issue by ghatighorias** [muak/AiForms.Renderers#28]
is there a way to hide the section title ?

**Comment by muak** [comment]
@ghatighorias 

There is no way to hide the section title.
But you can use a section header height instead of hiding.

please try like the following code:

```xml
<sv:SettingsView>    
    <sv:Section HeaderHeight="0">
        <sv:LabelCell Title="Label" ValueText="value" />
    </sv:Section>
</sv:SettingsView>
```

Thank you.

**Comment by ghatighorias** [comment]
i had to do some minor changes for this in the code but your suggestion is mostly working :).
thanks
