### ISSUE TITLE
PickerCell Issue

### ISSUE THREAD

**Issue by DanielSmith1239** [muak/AiForms.Renderers#3]
Hello,
I am running into an issue with the PickerCell. When I tap on the cell, no options from the ItemSource pop up. The cell never transitions to the picker view. Can you please help me out? My code is below. 

```                       
    new PickerCell() {
         MaxSelectedNumber = 1,
         Title = "Test",
         DisplayMember = "Title",
         SelectedItems = new ObservableCollection<CellTitle>() { new CellTitle("Hi") },
         ItemsSource = new ObservableCollection<CellTitle> { new CellTitle("Hi"), new CellTitle("no")},
         PageTitle = "Hi"
    }

    public class CellTitle
    {
        public string Title { get; set; }
        public string Placeholder { get; set; }

        public CellTitle(string title, string placeholder)
        {
            Title = title;
            Placeholder = placeholder;
        }

        public CellTitle(string title) : this(title, title) { }
    }
```

**Comment by muak** [comment]
@DanielSmith1239 
Hello.

As far as I read your code, there is one issue.
Each element of SelectedItems must be the same instance as each element of ItemsSource.

So your code is changed like this
```csharp
var source = new ObservableCollection<CellTitle> { new CellTitle("Hi"), new CellTitle("no")};
var selected = new ObservableCollection<CellTitle> {source[0]};
new PickerCell() {
         MaxSelectedNumber = 1,
         Title = "Test",
         DisplayMember = "Title",
         SelectedItems = selected,
         ItemsSource = source,
         PageTitle = "Hi"
}
```

For another possiblity, there is what a page containing PickerCell must belong a NavigationPage.

Please confirm them once.

**Comment by DanielSmith1239** [comment]
I tried the code that you posted and it didn't work. Also, it's already in a NavigationPage.

**Comment by DanielSmith1239** [comment]
Here is all of my code for this page:
````
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using LunchOrder.Models;
using Xamarin.Forms;

using AiForms.Renderers;

namespace LunchOrder.Views
{
    public partial class SelectMealOptionsPage : ContentPage
    {
        public Order order;
        ObservableCollection<CellTitle> source = new ObservableCollection<CellTitle> { new CellTitle("Hi"), new CellTitle("no") };

        private TableView tableView;

        public SelectMealOptionsPage()
        {
            InitializeComponent();
            SetupTableView();
            SetupContent();
        }

        private void SetupTableView()
        {
            ObservableCollection<CellTitle> selected = new ObservableCollection<CellTitle> { source[0] };

            tableView = new TableView()
            {
                Root = new TableRoot()
                {
                    new TableSection("Meals")
                    {
                        new PickerCell()
                        {
                            MaxSelectedNumber = 1,
                            Title = "Test",
                            DisplayMember = "Title",
                            SelectedItems = selected,
                            ItemsSource = source,
                            PageTitle = "Hi"
                        }
                    }
                },
                Intent = TableIntent.Form
            };
        }

        private void SetupContent()
        {
            Content = tableView;
        }
    }
}
`````

Please help as soon as possible. I am in a big hurry to complete this project.

**Comment by DanielSmith1239** [comment]
The cell is there, but it doesn't display options when I tap on it.

**Comment by DanielSmith1239** [comment]
Update: I tried changing the tableView to a settingsview, and now the cell doesn't even show up:

````
using System.Collections.ObjectModel;
using System.Linq;
using LunchOrder.Models;
using Xamarin.Forms;

using AiForms.Renderers;

namespace LunchOrder.Views
{
    public partial class SelectMealOptionsPage : ContentPage
    {
        public Order order;
        ObservableCollection<CellTitle> source = new ObservableCollection<CellTitle> { new CellTitle("Hi"), new CellTitle("no") };

        private SettingsView tableView;

        public SelectMealOptionsPage()
        {
            InitializeComponent();
            Title = "Test page title";
            SetupTableView();
            SetupContent();
        }

        private void SetupTableView()
        {
            ObservableCollection<CellTitle> selected = new ObservableCollection<CellTitle> { source[0] };

            tableView = new SettingsView()
            {
                Root = new SettingsRoot()
                {
                    new Section()
                    {
                        new PickerCell()
                        {
                            MaxSelectedNumber = 0,
                            Title = "Test",
                            DisplayMember = "Title",
                            SelectedItems = selected,
                            ItemsSource = source,
                            PageTitle = "Hi"
                        }
                    }
                },
                Intent = TableIntent.Form
            };
        }

        private void SetupContent()
        {
            Content = tableView;
        }
    }
}
````

**Comment by muak** [comment]
@DanielSmith1239 

SettingsView.Root is initialized in the constructor.
So the SettingsRoot doesn't have to create a new instance.

please  change this
```csharp
            tableView = new SettingsView { CellTitleColor = Color.Black }; //your option
            tableView.Root.Add(
                new Section("Meals")
                {
                    new PickerCell()
                    {
                        MaxSelectedNumber = 1,
                        Title = "Test",
                        DisplayMember = "Title",
                        SelectedItems = selected,
                        ItemsSource = source,
                        PageTitle = "Hi"
                    },
            });
```
This code was worked in my environment.
But I found such some bugs as the app crash when CellTitleColor isn't set.
Thanks for your report.
I'm going to fix these bugs and release a new version.

**Comment by DanielSmith1239** [comment]
When I try that, I run into another issue. Please see the attached video: https://we.tl/t0n3kOCeV7

Error message:
System.NullReferenceException: Object reference not set to an instance of an object
  at AiForms.Renderers.iOS.PickerTableViewController.Dispose (System.Boolean disposing) [0x00043] in <989fd8e596854757aea4f2f47e8f0ace>:0
  at Foundation.NSObject.Dispose () [0x00000] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/src/Foundation/NSObject2.cs:133
  at AiForms.Renderers.iOS.SettingsTableSource.RowSelected (UIKit.UITableView tableView, Foundation.NSIndexPath indexPath) [0x000f4] in <989fd8e596854757aea4f2f47e8f0ace>:0
  at at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/src/UIKit/UIApplication.cs:79
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/src/UIKit/UIApplication.cs:63
  at LunchOrder.iOS.Application.Main (System.String[] args) [0x00001] in /Users/danielsmith/Documents/Programs/C sharp/LunchOrder/iOS/Main.cs:17

**Comment by muak** [comment]
@DanielSmith1239 

Sorry, SettingViews Property had to be set the CellBackgroundColor.
```csharp
            tableView = new SettingsView { CellTitleColor = Color.Black,CellBackgroundColor=Color.White }; //your option
            tableView.Root.Add(
                new Section("Meals")
                {
                    new PickerCell()
                    {
                        MaxSelectedNumber = 1,
                        Title = "Test",
                        DisplayMember = "Title",
                        SelectedItems = selected,
                        ItemsSource = source,
                        PageTitle = "Hi"
                    },
            });
```

**Comment by DanielSmith1239** [comment]
That works, thank you. Is there a way to change the style of the picker's tableview to grouped, to match the style of the form?

**Comment by muak** [comment]
@DanielSmith1239 
It was good.

For now, PickerTableView style fixes grouped. 

As to detail label, If UseDescriptionAsValue is true, a description label can show selected items on only Android.
On iOS, there is no way to.

But I accepted them as requests.

**Comment by DanielSmith1239** [comment]
Thanks again. The style for the picker cells for me is not grouped. How do I change it?

**Comment by muak** [comment]
@DanielSmith1239 
I See. I had misunderstood it.

In order to do what you want to do, You have to use the CommandCell whose Command property is set a command of moving to the next page.
And the next page has to be used SettingsView or TableVIew and implements your own process.

I accepted it as a request too.

**Comment by DanielSmith1239** [comment]
How do I access the CommandCell that the PickerCell is using?

**Comment by muak** [comment]
@DanielSmith1239 
It is impossible to do what you want to do with PickerCell.
So such as my writing previous, you have to implement your picker cell your own way using a CommandCell and a TableView.

**Comment by DanielSmith1239** [comment]
Ah, ok I understand now. Thanks.

**Comment by muak** [comment]
@thinkaboutcsharp 

Thank you for trying this library.

As far as I read your error message, I wonder that DisplayMember property is not set to PickerCell.
I'm sorry, I don't know information more than this.

If the issue is not solved, will you please write more information that includes the XAML?
