### ISSUE TITLE
Behaviors

### ISSUE THREAD

**Issue by matteopiccioni** [muak/AiForms.Renderers#34]
Hello,
I'd like to use Behaviors for EntryCell,
For example:

`            <sv:EntryCell Title=...TextAlignment="End">
              <sv:EntryCell.Behaviors>  
                <local:NumberValidationBehavior />  
              </sv:EntryCell.Behaviors>  
            </sv:EntryCell>
`
Are there possibilities to use validation using Behaviors?
In your example you use reactive, but I cant use it

Thanks

**Comment by muak** [comment]
@matteopiccioni 
Hi.

Behaviors can be set only classes derived from VisualElement.
Since Cell isn't derived from it, can't apply Behaviors.

Thank you.

**Comment by matteopiccioni** [comment]
Thanks
