### ISSUE TITLE
PickerCell NullReferenceException

### ISSUE THREAD

**Issue by thinkaboutcsharp** [muak/AiForms.Renderers#41]
I'm trying SettingsView. It is interesting  to customize cell's detail. TextPickerCell is succeeded but PickerCell is failed by NullReferenceException in only iOS. Android is both succeeded.
I tried #3 way, still had error. What is a reason?

SettingsView ver.0.3.0
Visual Studio for Mac Community 2017

XAML:
<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:local="clr-namespace:XamarinStudy5" x:Class="XamarinStudy5.MainPage" xmlns:sv="clr-namespace:AiForms.Renderers;assembly=SettingsView">
    <StackLayout Padding="0, 40, 0, 0">
        <sv:SettingsView VerticalOptions="Center">
            <sv:SettingsView.Root>
                <sv:Section Title="Section">
                    <sv:TextPickerCell Title="TextPickerCell" Items="{Binding Items}" />
                    <sv:PickerCell Title="PickerCell" ItemsSource="{Binding ItemsSource}" SelectedItems="{Binding SelectedItems}" DisplayMember="Name"/>
                </sv:Section>
            </sv:SettingsView.Root>
        </sv:SettingsView>
    </StackLayout>
</ContentPage>

C#:
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Xamarin.Forms;

namespace XamarinStudy5
{
    public partial class MainPage : ContentPage
    {
        public IList<string> Items { get; } = new ObservableCollection<string>();
        public ObservableCollection<PickerItem> ItemsSource { get; } = new ObservableCollection<PickerItem>();
        public ObservableCollection<PickerItem> SelectedItems { get; set; } = new ObservableCollection<PickerItem>();

        public MainPage()
        {
            InitializeComponent();

            BindingContext = this;

            Items.Add("abc");
            Items.Add("def");

            ItemsSource.Add(new PickerItem { Name = "abc" });
            ItemsSource.Add(new PickerItem { Name = "def" });
        }

        public class PickerItem
        {
            public string Name { get; set; }
        }
    }
}

In iOS project, I wrote "AiForms.Renderers.iOS.SettingsViewInit.Init();".

Thank you. Please help me!

**Comment by thinkaboutcsharp** [comment]
Sorry, here is stacktrace.

System.NullReferenceException: Object reference not set to an instance of an object
  at AiForms.Renderers.iOS.SettingsTableSource+<>c__DisplayClass16_0.<RowSelected>b__0 () [0x00000] in <a4ca25561e124fb59ad7aff09aea38b0>:0
  at Foundation.NSAsyncActionDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/Foundation/NSAction.cs:152
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/UIKit/UIApplication.cs:79
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/UIKit/UIApplication.cs:63
  at XamarinStudy5.iOS.Application.Main (System.String[] args) [0x00001] in /Users/ryu/Dev/XamarinStudy5/XamarinStudy5.iOS/Main.cs:17

**Comment by muak** [comment]
@thinkaboutcsharp 

Thank you for trying this library.

As far as I read your error message, I wonder that DisplayMember property is not set to PickerCell.
I'm sorry, I don't know information more than this.

If the issue is not solved, will you please write more information that includes the XAML?

**Comment by thinkaboutcsharp** [comment]
Thank you. Very sorry. This is XAML.

<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:local="clr-namespace:XamarinStudy5" x:Class="XamarinStudy5.MainPage" xmlns:sv="clr-namespace:AiForms.Renderers;assembly=SettingsView">
    <StackLayout Padding="0, 40, 0, 0">
        <sv:SettingsView VerticalOptions="Center">
            <sv:SettingsView.Root>
                <sv:Section Title="Section">
                    <sv:TextPickerCell Title="TextPickerCell" Items="{Binding Items}" />
                    <sv:PickerCell Title="PickerCell" ItemsSource="{Binding ItemsSource}" SelectedItems="{Binding SelectedItems}" DisplayMember="Name"/>
                </sv:Section>
            </sv:SettingsView.Root>
        </sv:SettingsView>
    </StackLayout>
</ContentPa

**Comment by thinkaboutcsharp** [comment]
XAML is erased... I try again.

**Comment by thinkaboutcsharp** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:local="clr-namespace:XamarinStudy5" x:Class="XamarinStudy5.MainPage" xmlns:sv="clr-namespace:AiForms.Renderers;assembly=SettingsView">
    <StackLayout Padding="0, 40, 0, 0">
        <sv:SettingsView VerticalOptions="Center">
            <sv:SettingsView.Root>
                <sv:Section Title="Section">
                    <sv:TextPickerCell Title="TextPickerCell" Items="{Binding Items}" />
                    <sv:PickerCell Title="PickerCell" ItemsSource="{Binding ItemsSource}" SelectedItems="{Binding SelectedItems}" DisplayMember="Name"/>
                </sv:Section>
            </sv:SettingsView.Root>
        </sv:SettingsView>
    </StackLayout>
</ContentPage>
```

**Comment by muak** [comment]
@thinkaboutcsharp 

I tried running your code.
You don't have to write "<sv:SettingsView.Root>"  in your Xaml.
Removing these parts, it can correctly build and run the program.

```xml
<sv:Section Title="Section">
    <sv:TextPickerCell Title="TextPickerCell" Items="{Binding Items}" />
    <sv:PickerCell Title="PickerCell" ItemsSource="{Binding ItemsSource}" SelectedItems="{Binding SelectedItems}" DisplayMember="Name"/>
</sv:Section>
```

Please try it.

Thank you.

**Comment by thinkaboutcsharp** [comment]
@muak 
Thank you.
I removed "SettingsView.Root" tag. But I still can run app in Android, cannot run in iOS. I get NullReferenceException.
iOS simulator is broken?...
I always develop using Debug mode. I tried Release mode, other versions of iOS, nothing changed.

**Comment by muak** [comment]
@thinkaboutcsharp 

I'm awfully sorry, I don't know more than that.

The chances are that it might be solved if you remove your project debug/bin and obj folders entirely and then restart vs for mac.

Thanks.

**Comment by thinkaboutcsharp** [comment]
Thank you.
I tried remove build folders, remake solution, and same actions do on another mac, all failed.
So, I tried old version of SettingsView, I found one rule.
Until 2.5.0 app is down and Visual Studio freezes, above 2.6.0 get NullRef.
Do you know some relationships of VS settings or assemblies or Xcode settings?
Android do correct. Why not iOS...

**Comment by thinkaboutcsharp** [comment]
Sorry, one more question.

I got git clone from here. I build Debug mode and reference to local assemblies.
Still I get NullRef but I get further stacktrace too. Please see below. Do you find something?

System.NullReferenceException: Object reference not set to an instance of an object
  at AiForms.Renderers.iOS.SettingsTableSource+<>c__DisplayClass16_0.<RowSelected>b__0 () [0x00000] in /Users/ryu/Reference/AiForms.Renderers/SettingsView.iOS/SettingsTableSource.cs:289
  at Foundation.NSAsyncActionDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/Foundation/NSAction.cs:152
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/UIKit/UIApplication.cs:79
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/UIKit/UIApplication.cs:63
  at XamarinStudy5.iOS.Application.Main (System.String[] args) [0x00001] in /Users/ryu/OneDrive - hk sar baomin inc/Dev/XamarinStudy5/XamarinStudy5.iOS/Main.cs:17

**Comment by thinkaboutcsharp** [comment]
More information.
I did some Console.WriteLine. I got situation.

In SettingTableSource.RowSelected method, our target is PickerCell so jump to 278, call GetUINavigationController method, naviCtrl as return value is null. I tried comment-out line, null too.
GetUINavigationController method actually gets controller type of Xamarin.Forms.Platform.iOS.PlatformRenderer - not UINavigationController so try to search its children then call GetUINavigationController and return is null (TODO comment is here).

It is difficult to analyze why controller type is not UINavigationController. Do you have any idea?

**Comment by thinkaboutcsharp** [comment]
I succeeded?
In App.xaml.cs I write not MainPage = new MainPage() but MainPage = new NavigationPage(new MainPage()) app will run.
It is small different from my image.
Your sample uses Prism but for strictly right information I hope sample uses standard library as possible.

Thank you.

**Comment by muak** [comment]
@thinkaboutcsharp 

I'm awfully sorry,
I forgot the pre-requisite that the parent page must be a NavigationPage at all.
I will additionally write that in the readme.md.

In any case, I'm glad for your success.

Thank you for your many reports.
