### ISSUE TITLE
LabelCell Title Gets Cut Off

### ISSUE THREAD

**Issue by DanielSmith1239** [muak/AiForms.Renderers#5]
Please see the "g" in the following image for what I mean: https://we.tl/RviCn41GZG

**Comment by muak** [comment]
@DanielSmith1239 
I think it works correctly if HasUnevenRows turn true or RowHeight set some value.
Will you please try it.

**Comment by DanielSmith1239** [comment]
That fixed it, but am I able to have multiple line titles in the cells?

**Comment by muak** [comment]
@DanielSmith1239 
Sorry, Title can't be set multi-lines.

**Comment by DanielSmith1239** [comment]
Can I submit that as a request?

**Comment by muak** [comment]
@DanielSmith1239 
Yes, you can. Thank you.
